// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1, arg2, arg3) {
  return window['go']['main']['App']['Generate'](arg1, arg2, arg3);
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
