// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetLanguages():Promise<Array<string>>;

export function GetModels():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;
